// Auto-generated by scripts/sync-core.mjs - DO NOT EDIT DIRECTLY
export const COOKIE_RULES = [
  {
    "id": "redditp",
    "name": "RedditP NSFW Filter",
    "domains": [
      "redditp.com",
      "www.redditp.com"
    ],
    "targetUrl": "https://www.redditp.com/",
    "cookies": [
      {
        "name": "nsfwCookie",
        "value": "false",
        "domain": ".redditp.com",
        "path": "/",
        "secure": true,
        "sameSite": "lax",
        "expirationDays": 365
      }
    ]
  },
  {
    "id": "duckduckgo",
    "name": "DuckDuckGo Strict SafeSearch",
    "domains": [
      "duckduckgo.com"
    ],
    "targetUrl": "https://duckduckgo.com/",
    "cookies": [
      {
        "name": "p",
        "value": "1",
        "domain": ".duckduckgo.com",
        "path": "/",
        "secure": true,
        "sameSite": "lax",
        "expirationDays": 365
      }
    ],
    "queryParams": [
      {
        "param": "kp",
        "value": "1"
      },
      {
        "param": "p",
        "value": "1"
      }
    ]
  },
  {
    "id": "teddit",
    "name": "Teddit NSFW Disabled",
    "domains": [
      "teddit.net",
      "teddit.rawbit.ninja",
      "teddit.zaggy.nl",
      "teddit.hostux.net"
    ],
    "targetUrl": "https://teddit.net/",
    "cookies": [
      {
        "name": "nsfw_enabled",
        "value": "false",
        "domain": "",
        "path": "/",
        "secure": true,
        "sameSite": "lax",
        "expirationDays": 365
      }
    ]
  },
  {
    "id": "libreddit",
    "name": "LibReddit / Redlib Show NSFW Off",
    "domains": [
      "libreddit.kavin.rocks",
      "libreddit.spike.codes",
      "redlib.catsarch.com",
      "redlib.tux.pizza"
    ],
    "targetUrl": "https://libreddit.kavin.rocks/",
    "cookies": [
      {
        "name": "show_nsfw",
        "value": "off",
        "domain": "",
        "path": "/",
        "secure": true,
        "sameSite": "lax",
        "expirationDays": 365
      }
    ]
  },
  {
    "id": "bing",
    "name": "Bing Strict SafeSearch",
    "domains": [
      "bing.com",
      "www.bing.com"
    ],
    "targetUrl": "https://www.bing.com/",
    "cookies": [
      {
        "name": "SRCHHPGUSR",
        "value": "ADLT=STRICT",
        "domain": ".bing.com",
        "path": "/",
        "secure": true,
        "sameSite": "lax",
        "expirationDays": 365
      }
    ],
    "queryParams": [
      {
        "param": "adlt",
        "value": "strict"
      }
    ]
  },
  {
    "id": "qwant",
    "name": "Qwant Strict SafeSearch",
    "domains": [
      "qwant.com",
      "www.qwant.com"
    ],
    "targetUrl": "https://www.qwant.com/",
    "cookies": [
      {
        "name": "safe_search",
        "value": "2",
        "domain": ".qwant.com",
        "path": "/",
        "secure": true,
        "sameSite": "lax",
        "expirationDays": 365
      }
    ]
  },
  {
    "id": "ecosia",
    "name": "Ecosia Strict SafeSearch",
    "domains": [
      "ecosia.org",
      "www.ecosia.org"
    ],
    "targetUrl": "https://www.ecosia.org/",
    "cookies": [
      {
        "name": "safesearch",
        "value": "1",
        "domain": ".ecosia.org",
        "path": "/",
        "secure": true,
        "sameSite": "lax",
        "expirationDays": 365
      }
    ]
  },
  {
    "id": "invidious",
    "name": "Invidious Restricted Mode",
    "domains": [
      "yewtu.be",
      "invidious.snopyta.org",
      "invidious.kavin.rocks"
    ],
    "targetUrl": "https://yewtu.be/",
    "cookies": [
      {
        "name": "restricted_mode",
        "value": "on",
        "domain": "",
        "path": "/",
        "secure": true,
        "sameSite": "lax",
        "expirationDays": 365
      }
    ]
  },
  {
    "id": "proxitok",
    "name": "ProxiTok Safe Filter",
    "domains": [
      "proxitok.pabloferrero.org",
      "tok.habedieeh.re"
    ],
    "targetUrl": "https://proxitok.pabloferrero.org/",
    "cookies": [
      {
        "name": "proxitok_filter",
        "value": "1",
        "domain": "",
        "path": "/",
        "secure": true,
        "sameSite": "lax",
        "expirationDays": 365
      }
    ]
  }
];
export const BLOCKLIST_RULES = {
  "version": "1.0.0",
  "updatedAt": "2026-09-29T12:00:00Z",
  "categories": [
    "adult",
    "explicit"
  ],
  "domains": [
    "beeg.com",
    "cam4.com",
    "chaturbate.com",
    "livejasmin.com",
    "onlyfans.com",
    "pornhub.com",
    "redtube.com",
    "stripchat.com",
    "xhamster.com",
    "xnxx.com",
    "xvideos.com",
    "youporn.com"
  ]
};
export const SAFESEARCH_RULES = [
  {
    "id": 101,
    "priority": 10,
    "action": {
      "type": "redirect",
      "redirect": {
        "transform": {
          "queryTransform": {
            "addOrReplaceParams": [
              {
                "key": "safe",
                "value": "active"
              }
            ]
          }
        }
      }
    },
    "condition": {
      "urlFilter": "||google.com/search?*q=*",
      "resourceTypes": [
        "main_frame"
      ]
    }
  },
  {
    "id": 102,
    "priority": 10,
    "action": {
      "type": "redirect",
      "redirect": {
        "transform": {
          "queryTransform": {
            "addOrReplaceParams": [
              {
                "key": "safe",
                "value": "active"
              }
            ]
          }
        }
      }
    },
    "condition": {
      "urlFilter": "||google.*/search?*q=*",
      "resourceTypes": [
        "main_frame"
      ]
    }
  },
  {
    "id": 103,
    "priority": 10,
    "action": {
      "type": "redirect",
      "redirect": {
        "transform": {
          "queryTransform": {
            "addOrReplaceParams": [
              {
                "key": "adlt",
                "value": "strict"
              }
            ]
          }
        }
      }
    },
    "condition": {
      "urlFilter": "||bing.com/search?*q=*",
      "resourceTypes": [
        "main_frame"
      ]
    }
  },
  {
    "id": 104,
    "priority": 10,
    "action": {
      "type": "redirect",
      "redirect": {
        "transform": {
          "queryTransform": {
            "addOrReplaceParams": [
              {
                "key": "kp",
                "value": "1"
              },
              {
                "key": "p",
                "value": "1"
              }
            ]
          }
        }
      }
    },
    "condition": {
      "urlFilter": "||duckduckgo.com/?*q=*",
      "resourceTypes": [
        "main_frame"
      ]
    }
  },
  {
    "id": 501,
    "priority": 10,
    "action": {
      "type": "modifyHeaders",
      "requestHeaders": [
        {
          "header": "YouTube-Restrict",
          "operation": "set",
          "value": "Strict"
        }
      ]
    },
    "condition": {
      "urlFilter": "||youtube.com/*",
      "resourceTypes": [
        "main_frame",
        "sub_frame",
        "xmlhttprequest"
      ]
    }
  },
  {
    "id": 502,
    "priority": 10,
    "action": {
      "type": "modifyHeaders",
      "requestHeaders": [
        {
          "header": "YouTube-Restrict",
          "operation": "set",
          "value": "Strict"
        }
      ]
    },
    "condition": {
      "urlFilter": "||youtube-nocookie.com/*",
      "resourceTypes": [
        "main_frame",
        "sub_frame",
        "xmlhttprequest"
      ]
    }
  }
];
